// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0DuSVmClst-1ME8tce6hgkvc_5o2IFZE',
    appId: '1:649404506191:web:a67fbb63912fbeb8870a3a',
    messagingSenderId: '649404506191',
    projectId: 'flutter-note-app-6832e',
    authDomain: 'flutter-note-app-6832e.firebaseapp.com',
    storageBucket: 'flutter-note-app-6832e.appspot.com',
    measurementId: 'G-3PDPES59BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYYXTE5gyqVsuLWdy3Ajfgrt5U0QlaQI0',
    appId: '1:649404506191:android:19239e9958a94711870a3a',
    messagingSenderId: '649404506191',
    projectId: 'flutter-note-app-6832e',
    storageBucket: 'flutter-note-app-6832e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMq2hi6ye3QuDcQqNcRURHX50YIeBopHY',
    appId: '1:649404506191:ios:25ea3f83dcbc9b16870a3a',
    messagingSenderId: '649404506191',
    projectId: 'flutter-note-app-6832e',
    storageBucket: 'flutter-note-app-6832e.appspot.com',
    iosClientId: '649404506191-u9hk82ndvm13opgls0cqkve6d3vogi44.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMq2hi6ye3QuDcQqNcRURHX50YIeBopHY',
    appId: '1:649404506191:ios:25ea3f83dcbc9b16870a3a',
    messagingSenderId: '649404506191',
    projectId: 'flutter-note-app-6832e',
    storageBucket: 'flutter-note-app-6832e.appspot.com',
    iosClientId: '649404506191-u9hk82ndvm13opgls0cqkve6d3vogi44.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseNoteApp',
  );
}
